### ISSUE TITLE
Add to the commit team config

### ISSUE THREAD

**Issue by jean** [collective/collective.developermanual#1]
I'm a member of the organization at https://github.com/collective but the checkout links are read-only:
              https://github.com/collective/collective.developermanual

Looks like collective.developermanual needs to be added to https://github.com/organizations/collective/teams/69277 ?

**Comment by aclark4life** [comment]
Added. Let me know if it works.

**Comment by garbas** [comment]
script is not running every 10min ... yet (working on it tonight) ... told you to run script by hand for now
please do not change anything in teams that starts with "--auto"
