### ISSUE TITLE
Underline styles for chapter/section titles

### ISSUE THREAD

**Issue by glenfant** [collective/collective.developermanual#11]
Hi,

It seems that sections marking is not homogeneous across the documentation. Sometimes, level 1 sections are underlined with "=", sometimes with "-". And the "mess" continues for the sub(...)sections.

There is a pretty good conventions here http://sphinx.pocoo.org/rest.html#sections but perhaps we could have better suited ones clearly indicated in the "writing.txt" file https://github.com/collective/collective.developermanual/blob/master/source/introduction/writing.txt

Cheers.

**Comment by miohtama** [comment]
Please go ahead; suggest this change in the document.

I believe a lot of material is from the era when Sphinx guidelines, or Sphinx itself, did not exist and thus there were no one definitive style.

**Comment by jean** [comment]
On Mon, Jan 16, 2012 at 11:31 PM, Gilles Lenfant
reply@reply.github.com
wrote:

> It seems that sections marking is not homogeneous across the documentation.
> Sometimes, level 1 sections are underlined with "=", sometimes with "-". And
> the "mess" continues for the sub(...)sections.

Yes. This bugs me too, and I have been making them homogenous opportunistically
as I edit files.

To my eyes, "====" is obviously heavier, indicating more importance, than
"----" and as such should be used for top-level sections.

I've also been making indentation consistently 4 spaces from the left margin,
and for Python code.

> There is a pretty good conventions here
> http://sphinx.pocoo.org/rest.html#sections

This looks perfectly sane, and luckily in line with what I've been doing :-)

> clearly indicated in the "writing.txt" file
> https://github.com/collective/collective.developermanual/blob/master/source/introduction/writing.txt

Yes please. Your first link looks fine to me, we can link to that. We would
want to add usages not mentioned there, such as the "doc" role, as in:
  :doc:`ZCacheable </performance/ramcache>`

## 

jean                                              . .. .... //\\oo///\

**Comment by glenfant** [comment]
OK, I added a note about headings underline styles in the appropriate page.

@jean: I'd prefer to encourage the use of :ref:`someplace` and index / glossary related rules. But the index feature seems deactivated on this Sphinx (didn't investigate further why, because this is perhaps intentional, Mikko ?).

 Using paths that may change is evil. Sphinx has very nice hyperlink features from rules like :class:`full.dotted.name.SomeClass` and some others to the API doc built with sphinx.ext.autodoc and directives from :py: domain.

**Comment by miohtama** [comment]
I disabled the index untill we have something indexed there... now it looked like a ghost town and didn't really give good impression of for newcoming developers who'd like to dive into Plone...

**Comment by jean** [comment]
On Jan 19, 2012 12:52 AM, "Gilles Lenfant" <
reply@reply.github.com>
wrote:

> OK, I added a note about headings underline styles in the appropriate
> page.

The Sphinx page already specifies headings that way, no?

**Comment by glenfant** [comment]
@jean: It's just an applicable summary to this developer manual.

@miohtama: as long as you don't enable the index, nobody will add index related information :D . IMHO you should enable it to encourage contributors to fill it. Just my opinion...
