### ISSUE TITLE
Intersphinx documentation build

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#112]
How we can build individual Plone package documentation under collective-docs

Domen knows

**Comment by miohtama** [comment]
This is currently handled like this:

https://github.com/collective/collective.developermanual/blob/master/source/reference_manuals/active/writing/crosslinking.rst

**Comment by miohtama** [comment]
Currently handled with buildout, mr. developer and symlinks. 

Make sure mr. developer are scanned for each build.

**Comment by svx** [comment]
will close this, the new setup is almmost there and different :)
