### ISSUE TITLE
Change documentation language?

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#114]
Do we need to change our languages as our "integrators" are "developers" elsewhere?

**Comment by jean** [comment]
I think it's OK as long as we are consistent. If we decide there's a better term, search & replace and edit globally. Put terms in the glossary and link to that like :term:`integrator` the first time it's used in a chapter or where there's a likelihood of confusion.

**Comment by svx** [comment]
this is done in the new setup, so I will close this
