### ISSUE TITLE
Only one authorative place for system dependencies list when installing Plone

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#115]
Currently we have multiple places where apt-get poem for Ubuntu / Debian is told
- Unified installer README
- http://plone.org/documentation/manual/installing-plone/installing-on-linux-unix-bsd/debian-libraries
- http://collective-docs.readthedocs.org/en/latest/getstarted/installation.html#installing-plone-using-the-unified-unix-installer

To make sure that the information will stay updated. I'd take "unofficial" versions down and replace them with a link to the official version.

Steve: What you do think is the right place to host this information?

**Comment by polyester** [comment]
remember: the universal installer is not only used for 'developers', but also for quick appraisal. I woudn't want people who just want to test it out quickly go through the whole developer manual.

**Comment by miohtama** [comment]
@polyester Agreed. Good point!

**Comment by svx** [comment]
so what should we do ? leave one short howto on plone.org with a 'mini version' with a link to developer.plone.org for more into the deep info ?

**Comment by svx** [comment]
I reviewed both and the main difference is that we tell ppl on d.p.org to run plone as it's own user and also to install python-distribute python-dev

how about add these to: http://plone.org/documentation/manual/installing-plone/installing-on-linux-unix-bsd/debian-libraries and link for more information to d.p.org ?

**Comment by polyester** [comment]
that sounds like a plan.

**Comment by svx** [comment]
done !
