### ISSUE TITLE
Fix Sphinx errors

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#123]
We have Sphinx (restructured text) syntax errors in the manual. The goal is to have zero syntax errors: then we can have a robot to notify #plone-docs IRC channel if someone edits the content and leaves in syntax errors.

Syntax errors come from 
- Due to partially machine made migration from plone.org to collective.developermanual  
- Human errors
- Copy-pasted .rst content from somewhere else

This ticket is a master ticket to clean up syntax errors.
- Each participant will tell the name of the section they are working on in the comments
- Run make clean ; make html until your section is polished
- Do git push (no pull request needed)
- Repeat until collective.developermanual is clean from Sphinx errors

**Comment by domenkozar** [comment]
There is a way to configure sphinx to fail build if there are warnings, should we push that once it's cleaned?

**Comment by miohtama** [comment]
It's already on the other ticket and we'll have a Travis + IRc bot: https://github.com/collective/collective.developermanual/issues/95

**Comment by witekdev** [comment]
can use this as an indication of who is working on what: http://okfnpad.org/plone-tuneup

**Comment by witekdev** [comment]
Yeah, build successfull
zero errors! (at time of posting)

feeling invincible like - Catch the Ice Dude.
http://www.youtube.com/watch?v=zd7c5tQCs1I
(before he landed that is :)

time for bed..

**Comment by svx** [comment]
will close this, docs are on the move and the new setup is almost done and has already less errors than our current seup
