### ISSUE TITLE
Create instructions how to install a trunk version of add-on from Github

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#125]
See http://plone.293351.n2.nabble.com/General-Questions-f293352.html

**Comment by svx** [comment]
example question:
http://plone.293351.n2.nabble.com/Installing-a-product-from-Github-td7560973.html

**Comment by svx** [comment]
where to put it ? 
under getstarted ?

**Comment by miohtama** [comment]
I think a good candidate would be add-on quick installation manual

http://plone.org/documentation/kb/installing-add-ons-quick-how-to/

**Comment by miohtama** [comment]
Also install add-ons needs love http://plone.org/documentation/kb/add-ons/installing - opening a separate ticket

**Comment by svx** [comment]
done ! i added it to http://plone.org/documentation/kb/installing-add-ons-quick-how-to/
