### ISSUE TITLE
Update how to change logo for Plone 4

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#126]
Outdated, does not work with P4: http://plone.org/documentation/kb/change-the-logo-in-plone-3 

Breaks on title attribute

tal:content="context/@@plone_portal_state/portal_title"

**Comment by j-craig** [comment]
fixing

**Comment by j-craig** [comment]
plone.app.layout 2.1.5 changed the logo viewlet's portal_title attribute to navigation_root_title, so the document was not valid for plone >= 4.1.  I edited the document to fix it.
