### ISSUE TITLE
Hello World tutorial is not in correct place

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#130]
http://developer.plone.org/getstarted/helloworld/ should go to its own manual under reference manuals.

(Just git mv, update indexes)

Also someone should "test drive" this and see if this still works with the latest Plone versions.

**Comment by j-craig** [comment]
working through the tutorial...

**Comment by j-craig** [comment]
I couldn't get buildout.python to work on linux or windows, but other than that I got it working by skipping that step and building a virtualenv with the system python (2.7).

I'm going to move it now, then add some notes and fixes.

**Comment by miohtama** [comment]
Great work!

**Comment by aclark4life** [comment]
@j-craig Please open a buildout.python ticket if you think it's appropriate
