### ISSUE TITLE
Close too long 2nd level table of contents

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#135]
For example this page has too long TOC:

http://developer.plone.org/forms/index.html

1) Go through all second level pages in d.p.o

2) Check if TOC is too long

3) Set a depth limit of TOC to 1 in this case

**Comment by ddbeck** [comment]
Just in case anybody else is considering working on this: I have a branch with a series of fixes ready to go. I'm working on getting push access now.
