### ISSUE TITLE
Add backup section to hosting docs

### ISSUE THREAD

**Issue by smcmahon** [collective/collective.developermanual#139]
The production deployment docs need a backup section.

**Comment by miohtama** [comment]
There are related recipes clutterd around in unified installer, Zope section, plone.org kb articles and Database section.

**Comment by smcmahon** [comment]
The new section is complete.

Whatever there is in the way of other docs, it's not in developer.plone.org. Searches for "backup" and "restore" don't return any meaningful docs.
