### ISSUE TITLE
Move PFG docs to developermanual

### ISSUE THREAD

**Issue by smcmahon** [collective/collective.developermanual#140]
Current documentation under products/ploneformgen is too obscure for what's become a mainstream mechanism.

**Comment by aclark4life** [comment]
go go go

**Comment by miohtama** [comment]
@djay Has a Funnelweb scipt which can do initial scraping and raw conversion

**Comment by miohtama** [comment]
The proper place would be /reference_manuals/ section. It can also be external, hosted inside Products.PloneFormGen package (even preferred)

**Comment by svx** [comment]
done !
