### ISSUE TITLE
Merge admin-docs and porg.admin

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#141]
Two repos for same docs

https://github.com/plone/ploneorg.admin/commit/1608081b14d7ab821d1e6e3752400ac24c3bfe87

https://github.com/plone/admin-docs

https://github.com/plone/ploneorg.admin

**Comment by aclark4life** [comment]
This is done, sort of. admin-docs has been merged into ploneorg.admin/admin-docs. We can clean the rest up later.
