### ISSUE TITLE
doc.plone.org end user manual

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#142]
There is already Sphinxified version (as by @giacomos ) :

https://github.com/plone-it/collective.italiandocumentation/tree/english-version

To get this to docs.plone.org end user manual as Sphinx
- Allocate domain
- Create a Github project
- Create a buildout configuration on deus2 like d.p.o has
- Make redirects
- Add quick edit note, Google analytics tracker and other Sphinx nifties
- Setup Travis CI watch job
- Proof-read 
- Announce

**Comment by giacomos** [comment]
I'm going to create a github project on collective called "collective.usermanual". Currently I've sphinxified the latest version of the manual (Plone4), if we think it could be useful I can create a branch and sphinxify the 3rd version too

**Comment by djay** [comment]
On 17/11/2012, at 10:35 PM, Giacomo Spettoli notifications@github.com wrote:

> I'm going to create a github project on collective called "collective.usermanual". Currently I've sphinxified the latest version of the manual (Plone4), if we think it could be useful I can create a branch and sphinxify the 3rd version too

why sphixify the user manual too?

**Comment by giacomos** [comment]
Because it came for free as I had to sphinxify it for an italian project of documentation. I thought it was good to have all the documentation stored in the same way (the consistency doesn't happen often as it should in the Plone world)

**Comment by djay** [comment]
On 17/11/2012, at 11:57 PM, Giacomo Spettoli notifications@github.com wrote:

> Because it came for free as I had to sphinxify it for an italian project of documentation. I thought it was good to have all the documentation stored in the same way (the consistency doesn't happen often as it should in the Plone world)

Only if it means it will be maintained more and appear in the same place as the current user manual does on plone.org
The original intent of moving our developer documentation to sphinx was to increase the likelyhood of documentation getting maintained by developers. However the user documentation was getting maintained by the documentation team. This may have changed. 
Is there more chance of the user manual getting maintained?

**Comment by giacomos** [comment]
Well, first, for the end user point of view a sphinxified doc is more comfortable as it can be easily printed or read with ebook reader. For the mainteiner point of view, I think it isn't more uncomfortable, not very much at least.
And second, in the long run, this could be the first step for a single network of all the localized doc centers : the center of the star will be the english version, and than there should be references to all localized doc centers. For ex. the French doc is already centralized and sphinxified, the Italian doc is going in the same direction. It could be a real great value, the one that Plone is missing and the one that can give a great boost.

**Comment by giacomos** [comment]
@miohtama https://github.com/collective/collective.usermanual  <--- it seems I can't push to this repo yet, is there something that I'm missing?

**Comment by giacomos** [comment]
doc uploaded. now let's do the sysadmin part

**Comment by djay** [comment]
On 18/11/2012, at 11:23 AM, Giacomo Spettoli notifications@github.com wrote:

> Well, first, for the end user point of view a sphinxified doc is more comfortable as it can be easily printed as a pdf or read with ebook reader. For the mainteiner point of view, I think it isn't more uncomfortable, not very much at least.
> And second, in the long run, this could be the first step for a single network of all the localized doc centers : the center of the star will be the english version, and than there should be references to all localized doc centers. For ex. the French doc is already centralized and sphinxified, the Italian doc is going in the same direction (as I'm leading a team with that purpose)

So If thats the direction we are going, then one thing I've wondered if it could be done with sphinix is automate screenshots?
Anyone know of a plugin would let embed some kind of selenium or robot framework type instructions into a document to get it to create it's own screenshots from plone?
The reason is the screenshots in the user manual tend to get out of date and are hard to maintain. There probably aren't as many screenshots as there should be because of this. Also with translations, screenshots needing to be redone in the appropriate language is also more work.

**Comment by datakurre** [comment]
@tisto has been experimenting with robot framework and screenshots (I'd guess, with simply running test suites before generating docs and linking hard-coded screenshot filenames: selenium-screenshot-X.png).

I might be able to do a Sphinx-plugin to generate screenshots while generating docs, but I'm afraid, it would be cumbersome Sphinx-directive to configure and it would also take a long time to run (because of setting up the test environment separately for every screenshot).

So, configuration ideas for such a plugin are welcome :)

**Comment by djay** [comment]
On 26/11/2012, at 4:42 PM, Asko Soukka notifications@github.com wrote:

> @tisto has been experimenting with robot framework and screenshots (I'd guess, with simply running test suites before generating docs and linking hard-coded screenshot filenames: selenium-screenshot-X.png).
> 
> I might be able to do a Sphinx-plugin to generate screenshots while generating docs, but I'm afraid, it would be cumbersome Sphinx-directive to configure and it would also take a long time to run (because of setting up the test environment separately for every screenshot).
> 
> So, configuration ideas for such a plugin are welcome :)

I think your initial idea isn't too bad. Run a set of robot tests before running sphinx in order to generate the screenshots. At least that would work for.
@tisto: can we zoom the screenshots?

**Comment by djay** [comment]
On 26/11/2012, at 5:39 PM, Dylan Jay dylan@dylanjay.com wrote:

> On 26/11/2012, at 4:42 PM, Asko Soukka notifications@github.com wrote:
> 
> > @tisto has been experimenting with robot framework and screenshots (I'd guess, with simply running test suites before generating docs and linking hard-coded screenshot filenames: selenium-screenshot-X.png).
> > 
> > I might be able to do a Sphinx-plugin to generate screenshots while generating docs, but I'm afraid, it would be cumbersome Sphinx-directive to configure and it would also take a long time to run (because of setting up the test environment separately for every screenshot).
> > 
> > So, configuration ideas for such a plugin are welcome :)

BTW if you did want to embed it, it doesn't need to be slow. The builtin doctest extension collections all the doctests togeather and runs them all togeather at the end by the looks of it. But getting robot framework up and going inside a sphinx build seems like too big a challenge to me just for the convenience to embed robot commands inside the rst.

http://sphinx-doc.org/ext/doctest.html

> I think your initial idea isn't too bad. Run a set of robot tests before running sphinx in order to generate the screenshots. At least that would work for.
> @tisto: can we zoom the screenshots?

**Comment by datakurre** [comment]
Dylan Jay wrote:

> I think your initial idea isn't too bad. Run a set of robot tests 
> before running sphinx in order to generate the screenshots. At least 
> that would work for.

Yes, that would work already, and would not invent a yet another of 
writing/running RF tests.

When you use zope.testrunner + robotsuite for running robot tests, every 
test will be reported into its own directory under 
"parts/test/Test_Suite/Test_Name/" and you can tust that filenames won't 
change when you add more tests to make more screenshots.

(Robotsuite also merges test reports and copies 
selenium-screenshot-images under parts/test, but those merged reports 
can be ignored here.)

> @tisto: can we zoom the screenshots?

If not, we could write an extended Image directive with support for 
cropping images using PIL.

-Asko

**Comment by emanlove** [comment]
@tisto @datakurre - I too had been tossing around the idea of a Robot Framework screenshot library for documentation purposes. I put up some code which gives a basic concept sketch of what I expect the library to look like and functionality I want within it. See https://github.com/emanlove/robotframework-screencapturelibrary.

@tisto - Do you have anything more than the responsive design tests your were talking about? This is just a basic outline and am going to post more to the robotframework-developers list but I want to see first what overlap in ideas/code we have first.

**Comment by macagua** [comment]
We have the a Spanish version as Sphinx here

https://github.com/collective/collective.spanishdocumentation/tree/master/source/manuales/usando_plone3/

For generate Sphinx format from HTML, we uses a simple python script called html2rst.py that converts the format

**Comment by macagua** [comment]
Other good resource for plone user manual is this https://svn.plone.org/svn/collective/plone_manual_resources/ is a images repository of illustrations using into user manual in formats .AI and .SVG.

**Comment by djay** [comment]
On 27/11/2012, at 5:21 AM, "Leonardo J .Caballero G." <
notifications@github.com> wrote:

We have the a Spanish version as Sphinx here

https://github.com/collective/collective.spanishdocumentation/tree/master/source/manuales/usando_plone3/

For generate Sphinx format from HTML, we uses a simple python script called
html2rst.py that converts the format

I've now checked in code in the developer manual buildout.cfg which will
let you convert HTML sites into rst

 —
Reply to this email directly or view it on
GitHubhttps://github.com/collective/collective.developermanual/issues/142#issuecomment-10727060.

**Comment by svx** [comment]
all of this is now included in the new setup: github.com/plone/documentation so I will close this one here now
