### ISSUE TITLE
Please support local usage

### ISSUE THREAD

**Issue by muellert** [collective/collective.developermanual#150]
The latest version of the developer manual has two imho very undesirable properties that it didn't have some time ago:
- Nagging users to edit somewhere online by using a large piece of screen real estate for a yellow box, thus obscuring parts of the navigation tree.
- Trying to enforce online usage by redirecting to d.p.o on every page, thus making a local copy hard to use.

While I am confident that I could patch these things out, I'd rather have your opinion first.

**Comment by miohtama** [comment]
Hi,

The yellow box can be minized by clicking it and it stays minimized across page loads. If it doesn't then something is wrong.

collective.developermanual has support for file:// protocol usage and doesn't try to redirect you if you are accessing it as file:// or http://localhost. Please see

https://github.com/collective/collective.developermanual/blob/master/source/_static/plone.js#L20

But we can, in fact, remove now this Javascript as the readthedocs.org has kindly set Nginx redirects for us.

**Comment by muellert** [comment]
Thank you, I'll look into it.

**Comment by muellert** [comment]
I hoped to fix the problem using this:

```
diff --git a/source/_static/plone.js b/source/_static/plone.js
index 05735a3..5bb5f10 100644
--- a/source/_static/plone.js
+++ b/source/_static/plone.js
@@ -24,7 +24,8 @@ function preferPrimaryDomain() {
         return;
     }

-    if(window.location.hostname == "localhost") {
+    // if(window.location.hostname == "localhost") {
+    if(window.location.hostname.match('^([a-zA-Z0-9-]+|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+|[0-9a-fA-F\:])$')) {
         return;
     }
```

The intent is to classify not only "localhost", but also all unqualified names and bare IP numbers as "local". Unfortunately, this does not work - it looks like I looked at the wrong place.

In my local version, I can't click the menu.

**Comment by svx** [comment]
I can't reproduce that, it's working here I will code that ticket for now, feel free to reopen it
