### ISSUE TITLE
Revisited root installation recommendation

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#151]
Hi,

http://plone.org/documentation/manual/installing-plone/installing-on-linux-unix-bsd/root-or-user-install

We might want to revisit whether to suggest to install as root or not. 

Newcomers are more likely to break their buildouts and stuff when they mess as root. They don't know when to use user "plone" or when to use root. I have observed this practice be more fragile, causing headache when people don't know how to fix (chown) things and I hope we could probably adjust the text so that 
- If you are installing Plone for the first time(s)
- If you are not very advanced in Linux
- -> do normal user installation

**Comment by svx** [comment]
- 1 !

http://developer.plone.org/getstarted/installation.html#installing-plone-using-buildout-on-ubuntu-debian says:

" Note It is not recommended to run or install Plone as the root user. There is nothing in Plone requiring root privileges."
