### ISSUE TITLE
change python-distribute to python-setuptools debian/ubuntu

### ISSUE THREAD

**Issue by svx** [collective/collective.developermanual#168]
checked versions:

debian 6
debian  7
ubuntu 12.10

we have here: http://plone.org/documentation/manual/installing-plone/installing-on-linux-unix-bsd/debian-libraries under required packages

and here:

http://developer.plone.org/getstarted/installation.html

python-distribute

this is changed in above versions to: python-setuptools

the current instructions will still work but will give user a warning/info message, which is less nice :)

**Comment by miohtama** [comment]
Should we have a policy we support old versions, but have in comments that you need to use this package if you are using this old version X?

**Comment by svx** [comment]
Sounds good to me !
- change our howtos to python-setuptools
- add a comment that you have to use versions python-distribute, in older versions - maybe something like in older versions [like ubuntu lucid]python-setuptools was named python-distribute ?

on the other hand, who is using so old debian or ubuntu versions ? ah well it's in lucid and lucid server is supported until april 2015

if its ok with everyone i will do that sometime tonight (CET)

**Comment by svx** [comment]
fixed !
