### ISSUE TITLE
Errors in Epub version

### ISSUE THREAD

**Issue by fulv** [collective/collective.developermanual#18]
1. Go to http://readthedocs.org/projects/collective-docs/downloads/, and download the Epub version.
2. Load the Epub version on an iPad
3. Open it on the iPad in iBooks
## Result:

Most of the sections start with an error:

```
This page contains the following errors:
error on line 266 at column 11:  Opening and ending tag mismatch: br line 0 and body
Below is a rendering of the page up to the first error.
```

The line and column numbers are different in each error, but the message is the same.

Apart from the error itself, I haven't found anything missing.   The pdf version works fine on the iPad.
The Epub version also works fine on my Mac in Adobe Digital Editions.

**Comment by miohtama** [comment]
Lovely! Didn't know this is possible. Any idea how to fix this particular error?

**Comment by khink** [comment]
I don't get any errors when opening the collective-docs.epub using Calibre on Ubuntu 12.10. Is the bug still there on th iPad?

**Comment by aclark4life** [comment]
We might have lost epub-a-bility with the recent move

**Comment by witekdev** [comment]
This issue still exits, just checked on the IPad2, IBooks ver 3.0.2

Though in my case I got:

This page contains the following errors:
error on line 72 at column 34: Opening and ending tag mismatch: a line 0 and li
Below is a rendering of the page up to the first error.

**Comment by timgraham** [comment]
I think this is at least in part an issue with readthedocs. Django also uses them and our epub has a [similar problem](https://code.djangoproject.com/ticket/19967).

Sent a pull request to readthedocs to address the `<br>` issue: https://github.com/rtfd/readthedocs.org/pull/409

**Comment by miohtama** [comment]
Please note that developer.plone.org does manual Sphinx builds and is not using readthedocs.org

http://developer.plone.org/reference_manuals/active/writing/crosslinking.html#developer-plone-org-builds

**Comment by svx** [comment]
we are working on the new setup for docs, we will not fix that in this (current) setup
