### ISSUE TITLE
ubuntu is not always equal to debian or other linux os's

### ISSUE THREAD

**Issue by svx** [collective/collective.developermanual#193]
ubuntu is based on debian testing but that does not mean that there are always equal in terms of howtos ...
for example ubuntu has sudo installed per default, debian and centos are coming without sudo ...
lots of our howtos use ubuntu as example, this can be misleading for newbies, we should try to change that...
- we could say we use ubuntu as example os and you have to adopt that for your os
- we make the differences between os's more clear in our howtos

**Comment by miohtama** [comment]
You are right. Let's take a policy "Ubuntu is default Linux OS. Instructions may differ for other distributions."?

**Comment by svx** [comment]
yes +1 
If there is no veto I will update readme.rst and installation.rst

**Comment by svx** [comment]
done !
