### ISSUE TITLE
epub-support for collective.developermanual

### ISSUE THREAD

**Issue by andreasma** [collective/collective.developermanual#195]
It would be great to update the Sphinx configuration of collective.developermanual thus it also supports the creation of the epub file format.
Sphinx is able to export in that format. I tried this local with adding only three lines to the makefile and it worked.

**Comment by miohtama** [comment]
HI @andreasma 

Can you provide a patch through Github Pull Request mechanism?

**Comment by svx** [comment]
we will not fix that for this setup, we are on the move !
