### ISSUE TITLE
404 on some files

### ISSUE THREAD

**Issue by dayontwari** [collective/collective.developermanual#196]
On this page: http://developer.plone.org/plone_theme_development/diazo_theme_recipes/quick_test.html#procedure at the bottom, the link to the PDF ("View an explanatory diagram in PDF format") 404s. The file is diazothemeexplained.pdf, it doesn't show up on the live site, but it is in the repo under ./source/plone_theme_development/. See: l.79 ./source/plone_theme_development/diazo_theme_recipes/quick_test.rst

`View an explanatory diagram in PDF format <../diazothemeexplained.pdf>`_

The other file that 404s is diazothemexplained.png, which can be found in ./source/plone_theme_development/images

see l.76-77 ./source/plone_theme_development/diazo_theme_recipes/quick_test.rst

.. image:: ../images/diazothemeexplained-thumb.png
   :target: .. _clickToZoom: ../diazothemexplained.png

**Comment by svx** [comment]
this will not get fixed for this version of the docs, the new version is almost ready say please hold on !
