### ISSUE TITLE
Email and errors

### ISSUE THREAD

**Issue by lrowe** [collective/collective.developermanual#2]
The documentation at http://collective-docs.readthedocs.org/en/latest/misc/email.html is incorrect as it does not supply the `immediate=True` parameter which causes an email to be sent immediately (and any error raised) rather than sent at the transaction boundary or queued for later delivery.

**Comment by jean** [comment]
Tidied up the chapter.

**Comment by lrowe** [comment]
The immediate=True needs to go in MailHost.send() not when calling the template to generate the text...

**Comment by jean** [comment]
Ah, does that mean Products/MailHost/interfaces.py is out of date? (It doesn't mention `immediate`.) (Checked on 4.0.7)

**Comment by miohtama** [comment]
Updated docs related immediate keyword. Added just as a note as looks like interface description really doesn't tell how it funcs.

**Comment by miohtama** [comment]
Taking my word back: got Git conflict and didn't notice aclark's changes... cleaning up now.
