### ISSUE TITLE
source/components/zcml.rst refers to file which doesn't exist (serving/layers)

### ISSUE THREAD

**Issue by bdbaddog** [collective/collective.developermanual#22]
/Users/bdbaddog/devel/plone/collective.developermanual/source/components/zcml.rst:77: WARNING: unknown document: serving/layers

**Comment by bdbaddog** [comment]
I think this is the result of Jean's checking based on comments.. Please take a look.

**Comment by bdbaddog** [comment]
looks like different errors in master. closing.

**Comment by svx** [comment]
is this still valid ?

**Comment by svx** [comment]
i cant reproduce that, maybe it was an older version ?
