### ISSUE TITLE
Unified Installer readme points to outdated deployment doc

### ISSUE THREAD

**Issue by adaugherity** [collective/collective.developermanual#235]
From Plone-4.3.2-UnifiedInstaller/README.txt:

> If you are a deploying Plone for production, read
> `Basics of Plone Production Deployment <http://developer.plone.org/hosting/basics/index.html>`_
> before continuing.

This is apparently an outdated copy as the "edit on GitHub" link on that page (and any subpages) is a 404, but there's no other indication that these are not the current docs. Apparently the correct URL is http://developer.plone.org/reference_manuals/active/deployment/index.html, which has more up-to-date information.

As there's lots of versions of installer tarballs pointing to the outdated version, a redirect should be set up from the old URL to the new one (preferably with a regex catching subpages also) , and optionally updating the README file in the unified installer.  (Also, the 4.2.6 installer tarball uses http://collective-docs.readthedocs.org/en/latest/hosting/basics/index.html -- which redirects to the "bad" URL mentioned above.)

**Comment by svx** [comment]
Updated the Readme of Unified Installer: https://github.com/plone/Installers-UnifiedInstaller/blob/master/README.txt
