### ISSUE TITLE
Promote Archetypes Documentation

### ISSUE THREAD

**Issue by me-kell** [collective/collective.developermanual#245]
The documentation team marks some parts/technologies as old because "the team feels that it no longer reflect the modern Plone versions and best practices".
Among those technologies are archetypes, portlets, and the pluggable authentication service. Those technologies are still essential parts of Plone (also in the current Vesion 4.3.2) and unavoidable in "serious", "future proof" Plone projects.

Taking archetypes as example: The documentation do not reflect the fact that archetypes still are (and probably will be) the core technology for content in Plone (ATDocument, ATFolder, etc.).
This resulting in the necessity of finding good and updated documentation about archetypes (and all the related technologies, e.g. plone theming) and not only beeing told that this is "old" and that it will be replaced by "more modern" technologies, e.g. dexterity.
Furthermore the growing reference to grok in the documentation wrongly suggests that grok is part or is necessary for Plone development. As far as I know the Plone Core Team decided not to include dependencies on grok.

Don't take me wrong. Both dexterity and grok are very useful framewoks that deserve good documentation. But archetypes must not (yet) be relegated "beyond the point where the ancient dragons lie" and be suggested that they are "not recommended to be used in your active Plone development".
Therefore it seems to me that the manual should reflect this and promote the respective manual pages of archetypes to the section "Programming Plone".

**Comment by svx** [comment]
You are right ! We already fixed that in the new documentation setup, which will be online soon, so I will close that one here for now, thanks for your input !
