### ISSUE TITLE
Remove lenghty note "Edit this document..." from epub or make it a one-liner

### ISSUE THREAD

**Issue by marciomazza** [collective/collective.developermanual#39]
In http://readthedocs.org the generate HTML for the manual includes side note on every page saying "Edit this document... The source code of this file is hosted on GitHub."

There are  conveniently built PDF and epub versions at
http://readthedocs.org/projects/collective-docs/downloads/

The PDF does not contais the edit note, but the epub does. The note takes much screen real estate, which is something precious in a Kindle or other ebook readers.

I suggest the note is removed from the built epub.
Or maybe a little **one-liner** note could be put in its place.

**Comment by miohtama** [comment]
I did not know that ePub is generated from HTML. Any idea how to add Jinja condition IF NOT EPUB THEN....?

**Comment by svx** [comment]
we are moving to the new setup, this one will not get fixed on the current setup
