### ISSUE TITLE
Screencast tutorials for TTW Diazo and Dexterity

### ISSUE THREAD

**Issue by miohtama** [collective/collective.developermanual#96]
Short, on the order of 5 minute, screencasts showing the basics of TTW content and theming. End with pointers to written tutorials.

NutJob is very good at this if he's willing.

**Comment by svx** [comment]
+1

we need a place to put all the screencasts otherwise it will get messy and they will be all around the web on different locations

**Comment by emanlove** [comment]
@svx: You [mention](https://github.com/collective/collective.developermanual/issues/152#issuecomment-10883002) a Drupal user's experience in trying out Plone. [Here](http://drupalize.me/) is a website created by a local Drupal development shop, [Lullabot](http://www.lullabot.com/), that does a lot of educational videos and does Drupal training. This is an [example](http://drupalize.me/) of what can be done.

**Comment by svx** [comment]
its on the list so I will close this here
